# Generated by Django 5.2.7 on 2025-10-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=64)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rooms', models.CharField(blank=True, max_length=32)),
                ('total_area_m2', models.FloatField(blank=True, null=True)),
                ('living_area_m2', models.FloatField(blank=True, null=True)),
                ('kitchen_area_m2', models.FloatField(blank=True, null=True)),
                ('floor', models.CharField(blank=True, max_length=16)),
                ('floors_total', models.CharField(blank=True, max_length=16)),
                ('year_built', models.CharField(blank=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
